### ISSUE TITLE
G413 Silver - Stop Breathing

### ISSUE THREAD

**Issue by thereallinusrg** [MatMoul/g810-led#206]
So I tried to stop the breathing effect of my G413 Silver with the G413 Carbon command on Arch.
Sadly, that didn't work.
Is there a way to add support for the G413 Silver / port the Carbon device profile?
What information would I need to create a G413 Silver device profile?
The constant breathing is slowly driving me nuts.

**Comment by thereallinusrg** [comment]
I created a Wireshark dump for the G413 Silver:
[G413-Silver-Dump.zip](https://github.com/MatMoul/g810-led/files/4005926/G413-Silver-Dump.zip)

**Comment by MatMoul** [comment]
G413 seem supported, is this issue always relevent?

**Comment by thereallinusrg** [comment]
Yes, it seems that only the the G413 Carbon is supported, not the G413 Silver.

**Comment by MatMoul** [comment]
Sorry, G413 Carbon is supported but not Silver...
Your keyboard seem to be old...

**Comment by thereallinusrg** [comment]
Well, as old as the G413 Carbon. But yeah, oldish

**Comment by mrmusichead** [comment]
Having the same issue with the G413 Silver. I tried to modify the profile, and when I set the color to blue and restarted, the breathing stopped. The problem now is that I can't get the LEDs to light back up. I'm on Kubuntu 20.04. Also, I switched to Linux about 2 weeks ago from only using Windows, so I have next to no idea how to test the keyboard. Loving Linux otherwise though!

**Comment by MatMoul** [comment]
Seem @mrmusichead has replied :)
